version: '3.9'
services:
  api:
    build: ./backend
    container_name: stlmanager-api
    environment:
      - CACHE_DB_PATH=/app/data/cache.db
      - COLLECTION_ROOT=/mnt/CollectionSTL
    volumes:
      - ./data:/app/data
      - nas-share:/mnt/CollectionSTL
    ports:
      - '8091:8000'

  web:
    build: ./frontend
    container_name: stlmanager-web
    environment:
      - VITE_API_URL=http://localhost:8091
    ports:
      - '8090:80'

volumes:
  nas-share:
    driver: local
    driver_opts:
      type: cifs
      device: "//SERVEURPI/Fichiers3D/Fichiers3D"
      o: "username=${SMB_USER},password=${SMB_PASS}"