services:
  api:
    build: ./backend
    container_name: stlmanager-api
    environment:
      - CACHE_DB_PATH=/app/data/cache.db
      - COLLECTION_ROOT=/mnt/CollectionSTL
    volumes:
      - ./data:/app/data
      # Utiliser un disque SSD USB local (Windows)
      - "H:/Fichiers3D:/mnt/CollectionSTL:rw"
      # Alternative (commentée): partage SMB monté via CIFS
      # - nas-share:/mnt/CollectionSTL:rw
    ports:
      - '8091:8000'
    restart: unless-stopped

  web:
    build: ./frontend
    container_name: stlmanager-web
    environment:
      - VITE_API_URL=http://localhost:8091
    ports:
      - '8090:80'
    restart: unless-stopped

#volumes:
  # nas-share:
  #   driver: local
  #   driver_opts:
  #     type: cifs
  #     device: "//SERVEURPI/Fichiers3D"
  #     o: "username=${SMB_USER},password=${SMB_PASS},vers=3.0,file_mode=0777,dir_mode=0777"